providers = ["php"]

[phases.setup]
nixPkgs = ["php80", "php80Extensions.mbstring", "php80Extensions.xml", "php80Extensions.pdo", "php80Extensions.pdo_mysql", "php80Extensions.tokenizer", "php80Extensions.curl", "php80Extensions.openssl", "php80Extensions.bcmath", "php80Extensions.gd", "php80Extensions.zip", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = []

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
