[phases.setup]
nixPkgs = ["php81", "php81Extensions.mbstring", "php81Extensions.xml", "php81Extensions.pdo", "php81Extensions.pdo_pgsql", "php81Extensions.tokenizer", "php81Extensions.ctype", "php81Extensions.fileinfo", "php81Extensions.openssl", "php81Extensions.bcmath"]

[phases.build]
cmds = [
  "which php > .php_path && echo PHP path: $(which php) && php -v",
  "composer install --no-dev --no-scripts --no-interaction --optimize-autoloader",
  "npm install",
  "npm run production"
]

[start]
cmd = "node server.js"
